name: Release Action

on:
  workflow_dispatch:
  push:
    branches: ["main"]

concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    name: Test, Build, Tag and Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[release]') }}

    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - uses: actions/checkout@v6
      - uses: voidzero-dev/setup-vp@v1
        with:
          node-version-file: ".node-version"
          cache: true

      - name: Test
        run: vp check && vp test

      - name: Build
        run: vp pack

      - name: Tag and Release
        run: vp exec semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
